CREATE TABLE IF NOT EXISTS rating (
	rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	rating enum ('G', 'PG', 'PG-13', 'R', 'NC-17')
);

CREATE TABLE IF NOT EXISTS films (
	film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(50) NOT NULL,
	description varchar(200),
	releasedate date,
	duration integer CHECK (duration >= 0),
	rating_id integer REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS users (
	user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(40) NOT NULL,
	login varchar(50) NOT NULL,
	name varchar(50),
	birthday date
);

CREATE TABLE IF NOT EXISTS genres (
	genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genre enum ('Комедия', 'Драма', 'Мультфильм', 'Триллер', 'Документальный', 'Боевик')
);

CREATE TABLE IF NOT EXISTS films_genres (
	film_id integer REFERENCES films (film_id) ON DELETE CASCADE,
	genre_id integer REFERENCES genres (genre_id)
);

CREATE TABLE IF NOT EXISTS friendship_statuses (
	user_id integer REFERENCES users (user_id) ON DELETE CASCADE,
	friend_id integer REFERENCES users (user_id) ON DELETE CASCADE,
	status enum ('UNCONFIRMED', 'CONFIRMED', 'REJECTED')
);

CREATE TABLE IF NOT EXISTS likes (
	film_id integer REFERENCES films (film_id) ON DELETE CASCADE,
	user_id integer REFERENCES users (user_id) ON DELETE CASCADE
);